// import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar'
import './globals.css'
import './style/landing/header-slider.css'
import './style/landing/section-slider.css'
import './style/landing/service-slider.css'
import './style/landing/3d-slider.css'
import './style/project.css'
import './style/media.css'
import Footer from '@/components/footer'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'افق گستر ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body >
      <Navbar />
      {children}
      <Footer />
      </body>
    </html>
  )
}
