name: ci/cd

on:
  push:
    branches:
      - "main"

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       -
         name: Checkout
         uses: actions/checkout@v3
       -.
         name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       -
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
       -
         name: Build and push
         uses: docker/build-push-action@v4
         with:
           context: .
           file: ./Dockerfile
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/mainproject:latest   ## name of the repository in n
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: appleboy/ssh-action@master
      name: Docker-Compose Remote Deployment
      with:
        script: |
           chmod 400 $SSH_PRIVATE_KEY
           ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY root@192.168.1.8 "
           cd /root/mainproject &&
           docker compose pull &&
           docker compose up -d"
